---
- hosts: localhost
  collections:
    - virt_lightning.virt_lightning
  tasks:
    - name: Create the Debian 10 VM
      vm:
        distro: debian-10
        name: myvm
        state: present

    - name: Refresh inventory to ensure new instaces exist in inventory
      meta: refresh_inventory

    - debug: var=hostvars.myvm
    - name:
      command: uname -a
      delegate_to: myvm

    - name: Destroy the VM
      vm:
        name: myvm
        state: absent
